apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: si-demo
  namespace: openshift-gitops
spec:
  description: RHACM Service Interconnect PostgreSQL demonstration
  sourceRepos:
    - '*'
  destinations:
    - namespace: '*'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: si-demo-clusters
  namespace: openshift-gitops
spec:
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: name
              operator: In
              values:
                - cluster-pwv6d
                - cluster-7b6lh
---
apiVersion: apps.open-cluster-management.io/v1beta1
kind: GitOpsCluster
metadata:
  name: si-demo
  namespace: openshift-gitops
spec:
  argoServer:
    cluster: local-cluster
    argoNamespace: openshift-gitops
  placementRef:
    apiVersion: cluster.open-cluster-management.io/v1beta1
    kind: Placement
    name: si-demo-clusters
