apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: install-service-interconnect
  namespace: si-demo-policies
  annotations:
    policy.open-cluster-management.io/standards: GitOps
    policy.open-cluster-management.io/categories: Networking
    policy.open-cluster-management.io/controls: Operator lifecycle
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: install-service-interconnect
        spec:
          remediationAction: enforce
          severity: high
          pruneObjectBehavior: DeleteIfCreated
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: operators.coreos.com/v1alpha1
                kind: Subscription
                metadata:
                  name: skupper-operator
                  namespace: openshift-operators
                spec:
                  channel: stable-2.2
                  installPlanApproval: Automatic
                  name: skupper-operator
                  source: redhat-operators
                  sourceNamespace: openshift-marketplace
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: install-service-interconnect
  namespace: si-demo-policies
placementRef:
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
  name: si-demo-managed-clusters
subjects:
  - apiGroup: policy.open-cluster-management.io
    kind: Policy
    name: install-service-interconnect
