apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bookinfo-db-replication
  namespace: bookinfo
  annotations:
    argocd.argoproj.io/sync-wave: "-25"
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: demo-vault
  target:
    name: bookinfo-db-replication
    creationPolicy: Owner
  data:
    - secretKey: tls.crt
      remoteRef:
        key: bookinfo/replication
        property: tls.crt
    - secretKey: tls.key
      remoteRef:
        key: bookinfo/replication
        property: tls.key
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bookinfo-db-ca
  namespace: bookinfo
  annotations:
    argocd.argoproj.io/sync-wave: "-25"
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: demo-vault
  target:
    name: bookinfo-db-ca
    creationPolicy: Owner
  data:
    - secretKey: ca.crt
      remoteRef:
        key: bookinfo/replication
        property: ca.crt
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: service-interconnect-token-ca
  namespace: bookinfo
  annotations:
    argocd.argoproj.io/sync-wave: "-25"
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: demo-vault
  target:
    name: service-interconnect-token-ca
    creationPolicy: Owner
  data:
    - secretKey: ca
      remoteRef:
        key: service-interconnect/link
        property: ca
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: service-interconnect-token-metadata
  namespace: bookinfo
  annotations:
    argocd.argoproj.io/sync-wave: "-25"
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: demo-vault
  target:
    name: service-interconnect-token-metadata
    creationPolicy: Owner
  data:
    - secretKey: url
      remoteRef:
        key: service-interconnect/link-metadata
        property: url
    - secretKey: code
      remoteRef:
        key: service-interconnect/link-metadata
        property: code
