apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../common
  - site-config.yaml
  - external-secrets-site-b.yaml
  - service-interconnect.yaml
  - link-job.yaml
  - postgres-replica.yaml
