apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: demo-vault
  annotations:
    argocd.argoproj.io/sync-wave: "-30"
spec:
  provider:
    vault:
      server: http://vault.vault-demo.svc.cluster.local:8200
      path: secret
      version: v2
      auth:
        tokenSecretRef:
          name: vault-auth
          namespace: vault-demo
          key: token
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bookinfo-db-app
  namespace: bookinfo
  annotations:
    argocd.argoproj.io/sync-wave: "-25"
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: demo-vault
  target:
    name: bookinfo-db-app
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
      data:
        username: '{{ .username }}'
        password: '{{ .password }}'
        database: '{{ .database }}'
  data:
    - secretKey: username
      remoteRef:
        key: bookinfo/app
        property: username
    - secretKey: password
      remoteRef:
        key: bookinfo/app
        property: password
    - secretKey: database
      remoteRef:
        key: bookinfo/app
        property: database
